spring:
  profiles:
    active: dev
---

server:
  port: 8001
spring:
  profiles: dev
  application:
    name: PLAT-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
info:
  app.name: trade
  company.name: 嗨淘科技
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
---

server:
  port: 8002
spring:
  profiles: test
  application:
    name: PLAT-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
info:
  app.name: trade
  company.name: 嗨淘科技
  build.artifactId: $project.artifactId$
  build.version: $project.version$
