server:
  port: 9527
spring:
  profile: dev
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  prefix: "/trade"
  ignored-services: "*"
  routes:
    plat.serviceld: plat-service
    plat.path: /plat/**

---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-TEST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  prefix: "/trade"
  ignored-services: "*"
  routes:
    plat.serviceld: plat-service
    plat.path: /plat/**
